### ISSUE TITLE
enable bucket region lookup in createMessage()

### ISSUE THREAD

**Issue by camillacaros** [mapbox/s3touch#7]
I've run into the problem of wanting to s3touch an item in an s3bucket located in `us-east-1` & send work message to an SNS topic that is in `us-west-2`. I've set env var `AWS_DEFAULT_REGION=us-west-2` to override [default region var in s3touch](https://github.com/mapbox/s3touch/blob/master/index.js#L3) so that we have proper access to the SNS topic in `us-west-2`.

However, this region var also gets used in the createMessage() function to relay [bucket & object information](https://github.com/mapbox/s3touch/blob/master/index.js#L52) in the headObject request. This means, if default region is set to `us-west-2`, we are unable to access objects in `us-east-1` and receive `Error: Could not HEAD object ("301")`

In order to change this behavior, I'm going to work on updating the [createMessage() function](https://github.com/mapbox/s3touch/blob/master/index.js#L41) to lookup region for object request based on the region its parent bucket is housed in.

This should be able to be accomplished with an [`getBucketLocation` call](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getBucketLocation-property)

cc @yhahn

**Comment by camillacaros** [comment]
hm, i think the edit may actually need to be made earlier --- up at the top where the [s3 object is initiated](https://github.com/mapbox/s3touch/blob/master/index.js#L5)

**Comment by yhahn** [comment]
@camillacaros ugh, this may mean you need to create multiple s3 clients to use -- one for the region the bucket is in, and one for the region the topic is in.

**Comment by camillacaros** [comment]
y i'm not totally sure yet -- it looks like the `s3` object is just used for bucket access and the `sns` object is used for the topic, so we may be ok? working on tests right now

**Comment by yhahn** [comment]
o ya, you're right : )
